/**
 * Identity Domain
 *
 * 导出：
 * - 类型定义
 * - API 函数
 * - React Hooks
 */

export type {
  Identity,
  IdentityType,
  IdentityStatus,
  PresenceStatus,
  IdentityProfile,
  IdentityStats,
  IdentityCapabilities,
  IdentityRuntime,
  IdentitySession,
  IdentityCredentials,
  IdentityRelationships,
  IdentityReference,
  IdentityEvents,
  CreateIdentityInput,
  UpdateIdentityInput,
  IdentityQuery,
  BootstrapStatus,
  ManagementSessionSummary,
  AdminAccountSummary,
  OpenClawAgentSummary,
  OpenClawSessionSummary,
  OpenClawAgentFileSummary,
  OpenClawDreamPolicy,
  OpenClawDreamRunSummary,
  OpenClawDreamRunDetail,
  OpenClawDreamStepSummary,
  OpenClawAgent,
  OpenClawSession,
  OpenClawSessionCreateInput,
  OpenClawAgentFile,
  OpenClawDreamRun,
  OpenClawDreamStep,
  WorkbenchSessionSummary,
  WorkbenchMessageSummary,
  WorkbenchSessionCreateInput,
  WorkbenchMessageInput,
  WorkbenchMessageCreateResponse,
} from './types';

export type { AccessToken } from '@/domains/task/types';

export {
  identityApi,
  getBootstrapStatus,
  setupOwner,
  login,
  logout,
  getSession,
  getOpenClawAgents,
  getOpenClawAgent,
  createOpenClawAgent,
  updateOpenClawAgent,
  deleteOpenClawAgent,
  getOpenClawSessions,
  createOpenClawSession,
  getOpenClawDreamRuns,
  getOpenClawDreamRun,
  pauseOpenClawDreamRun,
  resumeOpenClawDreamRun,
  getOpenClawFiles,
  revokeOpenClawSession,
  getAgentWorkbenchSessions,
  createAgentWorkbenchSession,
  getWorkbenchSession,
  getWorkbenchMessages,
  sendWorkbenchMessage,
  getAdminAccounts,
  createAdminAccount,
  disableAdminAccount,
  getAccessTokens,
  createAccessToken,
  revealAccessToken,
  revokeAccessToken,
} from './api';

export {
  useBootstrapStatus,
  useSession,
  useLogin,
  useLogout,
  useOpenClawAgents,
  useOpenClawAgent,
  useCreateOpenClawAgent,
  useUpdateOpenClawAgent,
  useDeleteOpenClawAgent,
  useOpenClawSessions,
  useCreateOpenClawSession,
  useOpenClawDreamRuns,
  useOpenClawDreamRun,
  useOpenClawFiles,
  usePauseOpenClawDreamRun,
  useResumeOpenClawDreamRun,
  useRevokeOpenClawSession,
  useAgentWorkbenchSessions,
  useCreateAgentWorkbenchSession,
  useWorkbenchSession,
  useWorkbenchMessages,
  useSendWorkbenchMessage,
  useAdminAccounts,
  useCreateAdminAccount,
  useDisableAdminAccount,
  useAccessTokens,
  useCreateAccessToken,
  useRevealAccessToken,
  useRevokeAccessToken,
  refreshSession,
  refreshOpenClawAgents,
  refreshAdminAccounts,
  refreshAccessTokens,
  refreshOpenClawSessions,
  refreshOpenClawDreamRuns,
  refreshAgentWorkbenchSessions,
  refreshWorkbenchMessages,
  prefetchSession,
  prefetchOpenClawAgents,
  prefetchOpenClawSessions,
  prefetchOpenClawDreamRuns,
  prefetchAccessTokens,
} from './hooks';
