/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/admin/agent-invites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Invites */
    get: operations['list_invites_api_admin_agent_invites_get'];
    put?: never;
    /** Create Invite */
    post: operations['create_invite_api_admin_agent_invites_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agent-invites/{invite_id}/revoke': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revoke Invite */
    post: operations['revoke_invite_api_admin_agent_invites__invite_id__revoke_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agent-join-requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Join Requests */
    get: operations['list_join_requests_api_admin_agent_join_requests_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agent-join-requests/{request_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Join Request */
    get: operations['get_join_request_api_admin_agent_join_requests__request_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agent-join-requests/{request_id}/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Approve Join Request */
    post: operations['approve_join_request_api_admin_agent_join_requests__request_id__approve_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agent-join-requests/{request_id}/reject': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reject Join Request */
    post: operations['reject_join_request_api_admin_agent_join_requests__request_id__reject_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Agents */
    get: operations['list_agents_api_admin_agents_get'];
    put?: never;
    /** Create Agent */
    post: operations['create_agent_api_admin_agents_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/agents/{agent_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Agent */
    get: operations['get_agent_api_admin_agents__agent_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Agent */
    patch: operations['update_agent_api_admin_agents__agent_id__patch'];
    trace?: never;
  };
  '/api/admin/agents/{agent_id}/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Agent Tokens */
    get: operations['list_agent_tokens_api_admin_agents__agent_id__tokens_get'];
    put?: never;
    /** Issue Token */
    post: operations['issue_token_api_admin_agents__agent_id__tokens_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/audit-actions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Audit Actions */
    get: operations['list_audit_actions_api_admin_audit_actions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/audit-logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Audit Logs */
    get: operations['list_audit_logs_api_admin_audit_logs_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/audit-stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Audit Stats */
    get: operations['audit_stats_api_admin_audit_stats_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/bootstrap/init': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Bootstrap Init */
    post: operations['bootstrap_init_api_admin_bootstrap_init_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/bootstrap/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Bootstrap Status */
    get: operations['bootstrap_status_api_admin_bootstrap_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/management-tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Management Tokens */
    get: operations['list_management_tokens_api_admin_management_tokens_get'];
    put?: never;
    /** Create Management Token */
    post: operations['create_management_token_api_admin_management_tokens_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/management-tokens/{token_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Management Token */
    delete: operations['revoke_management_token_api_admin_management_tokens__token_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/management-tokens/{token_id}/rotate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate Management Token */
    post: operations['rotate_management_token_api_admin_management_tokens__token_id__rotate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Change Password */
    patch: operations['change_password_api_admin_password_patch'];
    trace?: never;
  };
  '/api/admin/secrets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Secrets */
    get: operations['list_secrets_api_admin_secrets_get'];
    put?: never;
    /** Create Secret */
    post: operations['create_secret_api_admin_secrets_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/secrets/reencrypt': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reencrypt Secrets */
    post: operations['reencrypt_secrets_api_admin_secrets_reencrypt_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/secrets/{secret_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Secret */
    get: operations['get_secret_api_admin_secrets__secret_id__get'];
    put?: never;
    post?: never;
    /** Delete Secret */
    delete: operations['delete_secret_api_admin_secrets__secret_id__delete'];
    options?: never;
    head?: never;
    /** Update Secret */
    patch: operations['update_secret_api_admin_secrets__secret_id__patch'];
    trace?: never;
  };
  '/api/admin/secrets/{secret_id}/value': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reveal Secret */
    get: operations['reveal_secret_api_admin_secrets__secret_id__value_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/security/revoke-all-tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Revoke All Tokens
     * @description Emergency kill switch: revoke every management and agent token at once.
     *
     *     Session-only on purpose — a leaked automation token must not be able to
     *     wipe every other credential. Sessions are covered by the password change
     *     flow instead, which revokes all sessions after verifying the password.
     */
    post: operations['revoke_all_tokens_api_admin_security_revoke_all_tokens_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/session': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current Session */
    get: operations['current_session_api_admin_session_get'];
    put?: never;
    post?: never;
    /** Logout */
    delete: operations['logout_api_admin_session_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/session/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations['login_api_admin_session_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/spaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Spaces */
    get: operations['list_spaces_api_admin_spaces_get'];
    put?: never;
    /** Create Space */
    post: operations['create_space_api_admin_spaces_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/spaces/{space_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Space */
    delete: operations['delete_space_api_admin_spaces__space_id__delete'];
    options?: never;
    head?: never;
    /** Update Space */
    patch: operations['update_space_api_admin_spaces__space_id__patch'];
    trace?: never;
  };
  '/api/admin/spaces/{space_id}/memberships': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Memberships */
    get: operations['get_memberships_api_admin_spaces__space_id__memberships_get'];
    /** Replace Memberships */
    put: operations['replace_memberships_api_admin_spaces__space_id__memberships_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List All Tokens */
    get: operations['list_all_tokens_api_admin_tokens_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tokens/{token_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke Token */
    delete: operations['revoke_token_api_admin_tokens__token_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tokens/{token_id}/grants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Grants */
    get: operations['get_grants_api_admin_tokens__token_id__grants_get'];
    /** Replace Grants */
    put: operations['replace_grants_api_admin_tokens__token_id__grants_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/admin/tokens/{token_id}/rotate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Rotate Token */
    post: operations['rotate_token_api_admin_tokens__token_id__rotate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/onboarding/v1/requests': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Join Request */
    post: operations['submit_join_request_api_onboarding_v1_requests_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/onboarding/v1/requests/{request_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Join Status */
    get: operations['get_join_status_api_onboarding_v1_requests__request_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/onboarding/v1/requests/{request_id}/credential': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Claim Credential */
    post: operations['claim_credential_api_onboarding_v1_requests__request_id__credential_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vault/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations['get_me_api_vault_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vault/secrets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Secrets */
    get: operations['list_secrets_api_vault_secrets_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vault/secrets/{secret_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Secret */
    get: operations['get_secret_api_vault_secrets__secret_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Secret */
    patch: operations['update_secret_api_vault_secrets__secret_id__patch'];
    trace?: never;
  };
  '/api/vault/secrets/{secret_id}/value': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Reveal Secret */
    get: operations['reveal_secret_api_vault_secrets__secret_id__value_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vault/spaces': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Spaces */
    get: operations['list_spaces_api_vault_spaces_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/vault/spaces/{space_id}/secrets': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Secret */
    post: operations['create_secret_api_vault_spaces__space_id__secrets_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Lightweight liveness probe.
     */
    get: operations['healthcheck_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/readyz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe
     * @description Deep health check verifying database and encryption service.
     */
    get: operations['readiness_check_readyz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/version': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Version info
     * @description Application version information.
     */
    get: operations['version_version_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminInviteCreate */
    AdminInviteCreate: {
      /** Label */
      label: string;
      /**
       * Role
       * @default reader
       * @enum {string}
       */
      role: 'reader' | 'contributor' | 'maintainer';
      /** Space Id */
      space_id?: string | null;
      /**
       * Ttl Seconds
       * @default 86400
       */
      ttl_seconds: number;
    };
    /** AdminInviteResponse */
    AdminInviteResponse: {
      /** Code */
      code: string;
      /** Created At */
      created_at: string;
      /**
       * Default Role
       * @enum {string}
       */
      default_role: 'reader' | 'contributor' | 'maintainer';
      /** Default Space Id */
      default_space_id: string | null;
      /** Expires At */
      expires_at: string;
      /** Id */
      id: string;
      /** Label */
      label: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'consumed' | 'revoked' | 'expired';
    };
    /** AdminInviteSummary */
    AdminInviteSummary: {
      /** Created At */
      created_at: string;
      /**
       * Default Role
       * @enum {string}
       */
      default_role: 'reader' | 'contributor' | 'maintainer';
      /** Default Space Id */
      default_space_id: string | null;
      /** Expires At */
      expires_at: string;
      /** Id */
      id: string;
      /** Label */
      label: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'consumed' | 'revoked' | 'expired';
    };
    /** AdminJoinRequestApprove */
    AdminJoinRequestApprove: {
      /** Role */
      role?: ('reader' | 'contributor' | 'maintainer') | null;
      /** Space Id */
      space_id?: string | null;
      /**
       * Token Name
       * @default initial
       */
      token_name: string;
    };
    /** AdminJoinRequestReject */
    AdminJoinRequestReject: {
      /** Reason */
      reason?: string | null;
    };
    /** AdminJoinRequestSummary */
    AdminJoinRequestSummary: {
      /** Agent Id */
      agent_id: string | null;
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Id */
      id: string;
      /** Invite Id */
      invite_id: string;
      /** Proposed Name */
      proposed_name: string;
      /** Rejection Reason */
      rejection_reason: string | null;
      /** Reviewed At */
      reviewed_at: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'approved' | 'rejected' | 'expired';
    };
    /** AdminSessionResponse */
    AdminSessionResponse: {
      /**
       * Auth Type
       * @enum {string}
       */
      auth_type: 'session' | 'management_token';
      /** Email */
      email: string;
      /** Id */
      id: string;
    };
    /** AdminUserResponse */
    AdminUserResponse: {
      /** Email */
      email: string;
      /** Id */
      id: string;
    };
    /** AgentCreate */
    AgentCreate: {
      /** Description */
      description?: string | null;
      /** Name */
      name: string;
    };
    /** AgentCredentialResponse */
    AgentCredentialResponse: {
      /** Agent Id */
      agent_id: string;
      /**
       * Status
       * @constant
       */
      status: 'approved';
      /** Token */
      token: string;
    };
    /** AgentJoinRequestCreate */
    AgentJoinRequestCreate: {
      /** Agent Name */
      agent_name: string;
      /** Description */
      description?: string | null;
      /** Invite Code */
      invite_code: string;
    };
    /** AgentJoinRequestResponse */
    AgentJoinRequestResponse: {
      /** Expires At */
      expires_at: string;
      /** Request Id */
      request_id: string;
      /** Request Secret */
      request_secret: string;
      /**
       * Status
       * @constant
       */
      status: 'pending';
    };
    /** AgentJoinStatusResponse */
    AgentJoinStatusResponse: {
      /** Agent Id */
      agent_id?: string | null;
      /** Reason */
      reason?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'pending' | 'approved' | 'rejected' | 'expired';
    };
    /** AgentPageResponse */
    AgentPageResponse: {
      /** Items */
      items: components['schemas']['AgentResponse'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** AgentResponse */
    AgentResponse: {
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'disabled';
      /** Updated At */
      updated_at: string;
    };
    /**
     * AgentSecretCreate
     * @description Agent contribution payload; the target Space comes from the URL.
     */
    AgentSecretCreate: {
      /** Description */
      description?: string | null;
      /** Documentation Url */
      documentation_url?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
      /** Name */
      name: string;
      /** Space Id */
      space_id?: string | null;
      /** Tags */
      tags?: string[];
      type: components['schemas']['SecretType'];
      /** Url */
      url?: string | null;
      /** Username */
      username?: string | null;
      /** Value */
      value: string;
    };
    /** AgentSecretUpdate */
    AgentSecretUpdate: {
      /** Description */
      description?: string | null;
      /** Documentation Url */
      documentation_url?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
      /** Name */
      name?: string | null;
      /** Space Id */
      space_id?: string | null;
      /** Tags */
      tags?: string[] | null;
      type?: components['schemas']['SecretType'] | null;
      /** Url */
      url?: string | null;
      /** Username */
      username?: string | null;
      /** Value */
      value?: string | null;
    };
    /** AgentTokenCreate */
    AgentTokenCreate: {
      /** Description */
      description?: string | null;
      /** Name */
      name: string;
      /** Ttl Seconds */
      ttl_seconds?: number | null;
    };
    /** AgentTokenOptionPageResponse */
    AgentTokenOptionPageResponse: {
      /** Items */
      items: components['schemas']['AgentTokenOptionResponse'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** AgentTokenOptionResponse */
    AgentTokenOptionResponse: {
      /** Agent Id */
      agent_id: string;
      /** Agent Name */
      agent_name: string;
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Expires At */
      expires_at: string | null;
      /** Id */
      id: string;
      /** Key Prefix */
      key_prefix: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'revoked';
    };
    /** AgentTokenPageResponse */
    AgentTokenPageResponse: {
      /** Items */
      items: components['schemas']['AgentTokenResponse'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** AgentTokenResponse */
    AgentTokenResponse: {
      /** Agent Id */
      agent_id: string;
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Expires At */
      expires_at: string | null;
      /** Id */
      id: string;
      /** Key Prefix */
      key_prefix: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'revoked';
    };
    /** AgentUpdate */
    AgentUpdate: {
      /** Description */
      description?: string | null;
      /** Name */
      name?: string | null;
      /** Status */
      status?: string | null;
    };
    /** AuditActionsResponse */
    AuditActionsResponse: {
      /** Items */
      items: string[];
    };
    /** AuditLogPageResponse */
    AuditLogPageResponse: {
      /** Items */
      items: components['schemas']['AuditLogResponse'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** AuditLogResponse */
    AuditLogResponse: {
      /** Action */
      action: string;
      /** Actor Id */
      actor_id: string | null;
      /** Actor Label */
      actor_label: string;
      /** Actor Type */
      actor_type: string;
      /** Created At */
      created_at: string;
      /** Id */
      id: string;
      /** Reason */
      reason: string | null;
      /** Request Id */
      request_id: string | null;
      /** Resource Id */
      resource_id: string | null;
      /** Resource Label */
      resource_label: string | null;
      /** Resource Type */
      resource_type: string | null;
      /**
       * Result
       * @enum {string}
       */
      result: 'success' | 'denied';
    };
    /** AuditStatsResponse */
    AuditStatsResponse: {
      /** Denied */
      denied: number;
      /** Granted */
      granted: number;
      /** Total */
      total: number;
      /** Value Reads */
      value_reads: number;
    };
    /** BootstrapRequest */
    BootstrapRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** BootstrapStatusResponse */
    BootstrapStatusResponse: {
      /** Bootstrap Token Required */
      bootstrap_token_required: boolean;
      /** Setup Required */
      setup_required: boolean;
    };
    /** GrantReplace */
    GrantReplace: {
      /** Secret Ids */
      secret_ids?: string[];
    };
    /** GrantResponse */
    GrantResponse: {
      /** Secret Ids */
      secret_ids: string[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** IssuedAgentTokenResponse */
    IssuedAgentTokenResponse: {
      /** Agent Id */
      agent_id: string;
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Expires At */
      expires_at: string | null;
      /** Id */
      id: string;
      /** Key Prefix */
      key_prefix: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'revoked';
      /** Token */
      token: string;
    };
    /** LoginRequest */
    LoginRequest: {
      /** Email */
      email: string;
      /** Password */
      password: string;
    };
    /** LoginResponse */
    LoginResponse: {
      /** Email */
      email: string;
      /** Status */
      status: string;
    };
    /** ManagementTokenCreate */
    ManagementTokenCreate: {
      /** Description */
      description?: string | null;
      /** Name */
      name: string;
      /** Ttl Seconds */
      ttl_seconds?: number | null;
    };
    /** ManagementTokenIssued */
    ManagementTokenIssued: {
      /** Expires At */
      expires_at: string | null;
      /** Id */
      id: string;
      /** Key Prefix */
      key_prefix: string;
      /** Name */
      name: string;
      /** Revoked At */
      revoked_at?: string | null;
      /** Token */
      token: string;
    };
    /** ManagementTokenPageResponse */
    ManagementTokenPageResponse: {
      /** Items */
      items: components['schemas']['ManagementTokenSummary'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ManagementTokenSummary */
    ManagementTokenSummary: {
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Expires At */
      expires_at: string | null;
      /** Id */
      id: string;
      /** Key Prefix */
      key_prefix: string;
      /** Last Used At */
      last_used_at: string | null;
      /** Name */
      name: string;
      /** Revoked At */
      revoked_at: string | null;
    };
    /** MembershipInput */
    MembershipInput: {
      /**
       * Role
       * @enum {string}
       */
      role: 'reader' | 'contributor' | 'maintainer';
      /**
       * Status
       * @default active
       * @enum {string}
       */
      status: 'active' | 'revoked';
      /** Token Id */
      token_id: string;
    };
    /** MembershipReplace */
    MembershipReplace: {
      /** Members */
      members: components['schemas']['MembershipInput'][];
    };
    /** PasswordChangeRequest */
    PasswordChangeRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** ReencryptResponse */
    ReencryptResponse: {
      /** Updated */
      updated: number;
    };
    /** RevokeAllTokensResponse */
    RevokeAllTokensResponse: {
      /** Agent Tokens Revoked */
      agent_tokens_revoked: number;
      /** Management Tokens Revoked */
      management_tokens_revoked: number;
    };
    /** SecretCreate */
    SecretCreate: {
      /** Description */
      description?: string | null;
      /** Documentation Url */
      documentation_url?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      };
      /** Name */
      name: string;
      /** Space Id */
      space_id?: string | null;
      /** Tags */
      tags?: string[];
      type: components['schemas']['SecretType'];
      /** Url */
      url?: string | null;
      /** Username */
      username?: string | null;
      /** Value */
      value: string;
    };
    /** SecretPageResponse */
    SecretPageResponse: {
      /** Items */
      items: components['schemas']['SecretResponse'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** SecretResponse */
    SecretResponse: {
      /** Created At */
      created_at: string;
      /** Created By Agent Id */
      created_by_agent_id: string | null;
      /** Description */
      description: string | null;
      /** Documentation Url */
      documentation_url: string | null;
      /** Id */
      id: string;
      /** Metadata */
      metadata: {
        [key: string]: unknown;
      };
      /** Name */
      name: string;
      /** Space Id */
      space_id: string | null;
      /** Tags */
      tags: string[];
      type: components['schemas']['SecretType'];
      /** Updated At */
      updated_at: string;
      /** Url */
      url: string | null;
      /** Username */
      username: string | null;
      /** Version */
      version: number;
    };
    /**
     * SecretType
     * @description Secret type constants.
     * @enum {string}
     */
    SecretType:
      | 'password'
      | 'api_key'
      | 'basic_auth'
      | 'bearer_token'
      | 'api_key_header'
      | 'oauth_token'
      | 'certificate'
      | 'ssh_key'
      | 'database_url'
      | 'custom';
    /** SecretUpdate */
    SecretUpdate: {
      /** Description */
      description?: string | null;
      /** Documentation Url */
      documentation_url?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: unknown;
      } | null;
      /** Name */
      name?: string | null;
      /** Space Id */
      space_id?: string | null;
      /** Tags */
      tags?: string[] | null;
      type?: components['schemas']['SecretType'] | null;
      /** Url */
      url?: string | null;
      /** Username */
      username?: string | null;
      /** Value */
      value?: string | null;
    };
    /** SecretValueResponse */
    SecretValueResponse: {
      /** Value */
      value: string;
    };
    /** SpaceCreate */
    SpaceCreate: {
      /** Description */
      description?: string | null;
      /** Name */
      name: string;
    };
    /** SpaceMembershipListResponse */
    SpaceMembershipListResponse: {
      /** Members */
      members: components['schemas']['SpaceMembershipResponse'][];
    };
    /** SpaceMembershipResponse */
    SpaceMembershipResponse: {
      /**
       * Role
       * @enum {string}
       */
      role: 'reader' | 'contributor' | 'maintainer';
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'revoked';
      /** Token Id */
      token_id: string;
    };
    /** SpaceUpdate */
    SpaceUpdate: {
      /** Description */
      description?: string | null;
      /** Name */
      name?: string | null;
      /** Status */
      status?: ('active' | 'archived') | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /** VaultAccessibleSpaceResponse */
    VaultAccessibleSpaceResponse: {
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Role
       * @enum {string}
       */
      role: 'reader' | 'contributor' | 'maintainer';
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'archived';
      /** Updated At */
      updated_at: string;
    };
    /** VaultIdentityResponse */
    VaultIdentityResponse: {
      /** Agent Id */
      agent_id: string;
      /** Agent Name */
      agent_name: string;
      /** Token Id */
      token_id: string;
      /** Token Name */
      token_name: string;
    };
    /** VaultSecretPageResponse */
    VaultSecretPageResponse: {
      /** Items */
      items: components['schemas']['VaultSecretResponse'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** VaultSecretResponse */
    VaultSecretResponse: {
      /**
       * Access Source
       * @enum {string}
       */
      access_source: 'direct' | 'space' | 'both';
      /** Created At */
      created_at: string;
      /** Created By Agent Id */
      created_by_agent_id: string | null;
      /** Description */
      description: string | null;
      /** Documentation Url */
      documentation_url: string | null;
      /** Id */
      id: string;
      /** Metadata */
      metadata: {
        [key: string]: unknown;
      };
      /** Name */
      name: string;
      /** Permissions */
      permissions: ('read' | 'create' | 'update')[];
      /** Space Id */
      space_id: string | null;
      /** Tags */
      tags: string[];
      type: components['schemas']['SecretType'];
      /** Updated At */
      updated_at: string;
      /** Url */
      url: string | null;
      /** Username */
      username: string | null;
      /** Version */
      version: number;
    };
    /** VaultSpaceListResponse */
    VaultSpaceListResponse: {
      /** Items */
      items: components['schemas']['VaultAccessibleSpaceResponse'][];
    };
    /** VaultSpacePageResponse */
    VaultSpacePageResponse: {
      /** Items */
      items: components['schemas']['VaultSpaceResponse'][];
    };
    /** VaultSpaceResponse */
    VaultSpaceResponse: {
      /** Created At */
      created_at: string;
      /** Description */
      description: string | null;
      /** Id */
      id: string;
      /** Name */
      name: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'active' | 'archived';
      /** Updated At */
      updated_at: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_invites_api_admin_agent_invites_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminInviteSummary'][];
        };
      };
    };
  };
  create_invite_api_admin_agent_invites_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminInviteCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminInviteResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  revoke_invite_api_admin_agent_invites__invite_id__revoke_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        invite_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_join_requests_api_admin_agent_join_requests_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminJoinRequestSummary'][];
        };
      };
    };
  };
  get_join_request_api_admin_agent_join_requests__request_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminJoinRequestSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  approve_join_request_api_admin_agent_join_requests__request_id__approve_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminJoinRequestApprove'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminJoinRequestSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reject_join_request_api_admin_agent_join_requests__request_id__reject_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminJoinRequestReject'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminJoinRequestSummary'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_agents_api_admin_agents_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        status?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_agent_api_admin_agents_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_agent_api_admin_agents__agent_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_agent_api_admin_agents__agent_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_agent_tokens_api_admin_agents__agent_id__tokens_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path: {
        agent_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentTokenPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  issue_token_api_admin_agents__agent_id__tokens_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        agent_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentTokenCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedAgentTokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_audit_actions_api_admin_audit_actions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditActionsResponse'];
        };
      };
    };
  };
  list_audit_logs_api_admin_audit_logs_get: {
    parameters: {
      query?: {
        result?: string | null;
        action?: string | null;
        actor_type?: string | null;
        actor_id?: string | null;
        actor_search?: string | null;
        resource_type?: string | null;
        resource_id?: string | null;
        resource_search?: string | null;
        created_from?: string | null;
        created_to?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditLogPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  audit_stats_api_admin_audit_stats_get: {
    parameters: {
      query?: {
        created_from?: string | null;
        created_to?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuditStatsResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bootstrap_init_api_admin_bootstrap_init_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BootstrapRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminUserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  bootstrap_status_api_admin_bootstrap_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['BootstrapStatusResponse'];
        };
      };
    };
  };
  list_management_tokens_api_admin_management_tokens_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManagementTokenPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_management_token_api_admin_management_tokens_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ManagementTokenCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManagementTokenIssued'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  revoke_management_token_api_admin_management_tokens__token_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rotate_management_token_api_admin_management_tokens__token_id__rotate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ManagementTokenIssued'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_password_api_admin_password_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PasswordChangeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_secrets_api_admin_secrets_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        search?: string | null;
        type?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_secret_api_admin_secrets_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SecretCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reencrypt_secrets_api_admin_secrets_reencrypt_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReencryptResponse'];
        };
      };
    };
  };
  get_secret_api_admin_secrets__secret_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_secret_api_admin_secrets__secret_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_secret_api_admin_secrets__secret_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SecretUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reveal_secret_api_admin_secrets__secret_id__value_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretValueResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  revoke_all_tokens_api_admin_security_revoke_all_tokens_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RevokeAllTokensResponse'];
        };
      };
    };
  };
  current_session_api_admin_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSessionResponse'];
        };
      };
    };
  };
  logout_api_admin_session_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  login_api_admin_session_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_spaces_api_admin_spaces_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSpacePageResponse'];
        };
      };
    };
  };
  create_space_api_admin_spaces_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SpaceCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSpaceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_space_api_admin_spaces__space_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        space_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_space_api_admin_spaces__space_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        space_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SpaceUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSpaceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_memberships_api_admin_spaces__space_id__memberships_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        space_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SpaceMembershipListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  replace_memberships_api_admin_spaces__space_id__memberships_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        space_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MembershipReplace'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SpaceMembershipListResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_all_tokens_api_admin_tokens_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentTokenOptionPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  revoke_token_api_admin_tokens__token_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_grants_api_admin_tokens__token_id__grants_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GrantResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  replace_grants_api_admin_tokens__token_id__grants_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GrantReplace'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['GrantResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  rotate_token_api_admin_tokens__token_id__rotate_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['IssuedAgentTokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  submit_join_request_api_onboarding_v1_requests_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentJoinRequestCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentJoinRequestResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_join_status_api_onboarding_v1_requests__request_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentJoinStatusResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  claim_credential_api_onboarding_v1_requests__request_id__credential_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        request_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentCredentialResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me_api_vault_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultIdentityResponse'];
        };
      };
    };
  };
  list_secrets_api_vault_secrets_get: {
    parameters: {
      query?: {
        space_id?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSecretPageResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_secret_api_vault_secrets__secret_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSecretResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_secret_api_vault_secrets__secret_id__patch: {
    parameters: {
      query?: never;
      header: {
        'If-Match': number;
      };
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentSecretUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSecretResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reveal_secret_api_vault_secrets__secret_id__value_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        secret_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SecretValueResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_spaces_api_vault_spaces_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSpaceListResponse'];
        };
      };
    };
  };
  create_secret_api_vault_spaces__space_id__secrets_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        space_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AgentSecretCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VaultSecretResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  healthcheck_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
  readiness_check_readyz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  version_version_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: string;
          };
        };
      };
    };
  };
}
